spring.application.name=finance-java

# Aqui o Spring vai olhar para o seu arquivo .env e pegar o valor de SUPABASE_URL
spring.datasource.url=${SUPABASE_URL}

# Aqui ele pega o SUPABASE_USER
spring.datasource.username=${SUPABASE_USER}

# E aqui a senha SUPABASE_PASS
spring.datasource.password=${SUPABASE_PASS}

spring.datasource.driverClassName=org.postgresql.Driver

# Hibernate Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080